replicaCount: 1

gateway:
  image:
    repository: tunisterk/go-app
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080
  service:
    type: ClusterIP
    port: 80

employeeService:
  image:
    repository: tunisterk/go-services
    tag: latest
    pullPolicy: IfNotPresent
  port: 8081
  
  service:
    type: ClusterIP
    port: 80

namespace: employee-platform


ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip