apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: {{ .Values.namespace }}
  labels:
    app: employee-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.employeeService.service.port }}
      targetPort: {{ .Values.employeeService.port }}
  selector:
    app: employee-service
  type: {{ .Values.employeeService.service.type }}