apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: {{ .Values.namespace }}

  labels:
    app: employee-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: {{ .Values.employeeService.image.repository }}:{{ .Values.employeeService.image.tag}}
        imagePullPolicy:  {{ .Values.employeeService.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.employeeService.port }}
