apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  namespace: {{ .Values.namespace }} 
  labels:
    app: go-web-app
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.gateway.port }}
