apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  namespace: {{ .Values.namespace }}
  labels:
    app: go-web-app
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.port }}
  selector:
    app: go-web-app